# Recopilación de datos
## Es un historia de clientes telecom_churn.csv
* gender
* tenure: Cantidd de meses que el cliente usa el servicio
* montlyCharges: cargos mensuales
* totalCharges: Total pagado por el cliente
* contract: tipo de contrato del cliente
* InternetServices: tipo de servicio de internet contratado
* Churn: abandono

# Importación de librerías

In [1]:
import pandas as pd
import numpy as np

# Visualización
import matplotlib.pyplot as plt

# Preprocesamiento
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# División de datos
from sklearn.model_selection import train_test_split

# Modelo
from sklearn.ensemble import RandomForestClassifier

# Métricas
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Validación
from sklearn.model_selection import cross_val_score

print("\n LIBRERÍAS CARGADAS CORRECTAMENTE !!!!!!!")

 LIBRERÍAS CARGADAS CORRECTAMENTE !!!!!!!

# Carga del DataSet

In [3]:
datos = pd.read_csv("telecom_churn.csv")

# Mostrar primeras filas
display(datos.head())
# Mostrar ultimas filas
display(datos.tail())
# Mostrar aleatorio
display(datos.sample(5))

,gender,tenure,MonthlyCharges,TotalCharges,Contract,InternetService,Churn
0,Male,4,34.69,102.71,Two year,Fiber optic,1
1,Male,55,56.56,3084.07,Month-to-month,DSL,0
2,Male,70,56.95,3964.32,One year,DSL,0
3,Male,55,39.33,2208.87,One year,Fiber optic,0
4,Male,49,109.32,5367.05,Month-to-month,Fiber optic,0

,gender,tenure,MonthlyCharges,TotalCharges,Contract,InternetService,Churn
1195,Female,54,36.29,1997.27,One year,DSL,0
1196,Female,29,65.61,1875.72,Month-to-month,No,0
1197,Male,62,68.44,4230.87,Two year,Fiber optic,0
1198,Male,47,75.05,3532.82,Month-to-month,DSL,1
1199,Female,25,74.76,1854.99,Two year,No,0

,gender,tenure,MonthlyCharges,TotalCharges,Contract,InternetService,Churn
283,Female,54,98.34,5301.40,Month-to-month,Fiber optic,1
1168,Female,25,93.77,2375.09,Month-to-month,No,1
1043,Female,37,79.01,2891.56,Month-to-month,DSL,0
701,Male,45,62.11,2813.73,One year,Fiber optic,0
297,Female,5,89.76,409.53,Month-to-month,Fiber optic,1

# Exploración inicial

In [4]:
print("\n INFORMACION DEL DATASET")
print("===================================\n")
print(datos.info())

print("\n ESTADISTICAS DEL DATA SET")
print("===================================\n")
display(datos.describe())

print("\n VALORES NULOS POR CAMPO")
print("===================================\n")
print(datos.isnull().sum())

 INFORMACION DEL DATASET
===================================

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           1200 non-null   str
 1   tenure           1200 non-null   int64
 2   MonthlyCharges   1200 non-null   float64
 3   TotalCharges     1200 non-null   float64
 4   Contract         1200 non-null   str
 5   InternetService  1200 non-null   str
 6   Churn            1200 non-null   int64
dtypes: float64(2), int64(2), str(3)
memory usage: 65.8 KB
None

 ESTADISTICAS DEL DATA SET
===================================

            tenure  MonthlyCharges  TotalCharges        Churn
count  1200.000000     1200.000000   1200.000000  1200.000000
mean     36.875000       64.221175   2368.704300     0.408333
std      20.645934       23.471789   1641.425281     0.491730
min       1.000000       20.040000      7.570000     0.000000
25%      18.000000       46.262500   1035.030000     0.000000
50%      37.000000       63.765000   2078.625000     0.000000
75%      55.250000       79.122500   3407.220000     1.000000
max      72.000000      120.000000   8418.100000     1.000000

 VALORES NULOS POR CAMPO
===================================

gender             0
tenure             0
MonthlyCharges     0
TotalCharges       0
Contract           0
InternetService    0
Churn              0
dtype: int64

# 2. Limpieza y preprocesamiento
## En datos reales existen
* valores nulos
* errores
* duplicados
* inconsistentes
* ruido

In [6]:
datos = datos.dropna()
print("\n VALORES NULOS ELIMINADOS ----->\n")

 VALORES NULOS ELIMINADOS ----->

## Eliminación de duplicados

In [7]:
datos = datos.drop_duplicates()
print("\n VALORES DUPLICADOS ELIMINADOS ====>\n")

 VALORES DUPLICADOS ELIMINADOS ====>

## Conversión de variables categóricas

In [8]:
encoder = LabelEncoder()

columnas_categoricas = [
    "gender",
    "Contract",
    "InternetService"
]

for columna in columnas_categoricas:
    datos[columna] = encoder.fit_transform(datos[columna])

display(datos.tail())
print("== REALIZADO LA CONVERSION EN: gender, Contract y InternetService ==")

,gender,tenure,MonthlyCharges,TotalCharges,Contract,InternetService,Churn
1195,0,54,36.29,1997.27,1,0,0
1196,0,29,65.61,1875.72,0,2,0
1197,1,62,68.44,4230.87,2,1,0
1198,1,47,75.05,3532.82,0,0,1
1199,0,25,74.76,1854.99,2,2,0

== REALIZADO LA CONVERSION EN: gender, Contract y InternetService ==

# Selección de variables
## Variables predictoras

In [9]:
X = datos[
    [
        "gender",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "Contract",
        "InternetService"
    ]
]
print("\n Seleccionado...! las variables independientes ====>")

 Seleccionado...! las variables independientes ====>

## Variable objetivo

In [10]:
y = datos["Churn"]
print("\n Definido---! la variable dependiente ====>")

 Definido---! la variable dependiente ====>

## Normalización de datos

In [11]:
scaler = StandardScaler()

X = scaler.fit_transform(X)
print("\n APLICADO LA NORMALIZACION AL DATA SET")

 APLICADO LA NORMALIZACION AL DATA SET

## 3. División de datos
### Lo dividimos en
* Entrenamiento
* Prueba
### Generalmente:
* 80% entrenamiento
* 20% prueba

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
print("\n REALIZADO LA DIVISION 80% PARA EL ENTRENAMIENTO, 20% PARA PRUEBA>")

 REALIZADO LA DIVISION 80% PARA EL ENTRENAMIENTO, 20% PARA PRUEBA>

## 4. Entrenamiento del algoritmo
### En esta etapa se aprende patrones automáticamente
### Se usará RandomForest
* Alta precisión
* Robustez
* Capacidad para manejar múltiples valores
* Reducción de overfitting
## Creación del modelo

In [13]:
modelo = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
print("\n MODELO CREADO.....!")

 MODELO CREADO.....!

## Entrenamiento

In [14]:
modelo.fit(X_train, y_train)
print("\n MODELO ENTRENDO.....!\n")

 MODELO ENTRENDO.....!

Durante esta fase:
* El algoritmo analiza ejemplos
* Ajusta parámetros internos
* Identifica patrones
* Genera árboles de decisión
* Optimiza predicciones

## 5. Generación del modelo
Despues del entrenamiento se obtiene un modelo entrenado capaz de predecir nuevos casos
## Realizar predicciones

In [15]:
predicciones = modelo.predict(X_test)

print("\n PREDICCION.....!, DE LOS PRIMEROS.....")
print(predicciones[:7])

 PREDICCION.....!, DE LOS PRIMEROS.....
[0 0 0 0 1 1 0]

Si sale 1: posible abandono; con 0: cliente estable

## Ejemplo de predicción individual

In [16]:
# LOS DATOS CORRESPONDEN A (gender,tenure,MonthlyCharges,TotalCharges,Contract,InternetService)

nuevo_cliente = pd.DataFrame([{
    'gender': 1,
    'tenure': 12,
    'MonthlyCharges': 80,
    'TotalCharges': 1200,
    'Contract': 0,
    'InternetService': 1
}])

nuevo_cliente = scaler.transform(nuevo_cliente)

resultado = modelo.predict(nuevo_cliente)

print("\n POSIBLE ESTADO DEL NUEVO CLIENTE ===> ",resultado)

 POSIBLE ESTADO DEL NUEVO CLIENTE ===>  [1]